import "./style.scss";
import LayoutMargin from "@/components/LayoutMargin";
import Navbar from "@/components/Navbar/Navbar";
import CategoryContextProvider from "@/context/CategoryContextProvider";

export const metadata = {
  title: "FastDiag",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CategoryContextProvider>
          <Navbar />
          <LayoutMargin>{children}</LayoutMargin>
        </CategoryContextProvider>
      </body>
    </html>
  );
}
